#!/usr/bin/env bash

source function/text/repeat
source function/value/empty

text::header() {
  local message=$1
  local length=${#message}

  if value::empty "$message"; then
    echo '**********'
  else
    text::repeat $((length + 4)) '*'
    echo
    echo "* $message *"
    text::repeat $((length + 4)) '*'
    echo
  fi
}
