#!/usr/bin/env bash

source function/command/exists
source function/file/empty

homebrew_formula='git'
apt_package='git'

recommended=(git-lfs)

configure() {
  echo "[git] setting up .gitconfig ..."
  ./git/gitconfig.sh

  if command::exists curl; then
    echo "[git] setting up .gitignore"
    if file::empty "~/.gitignore"; then
      echo >> ~/.gitignore
    fi

    case "$(platform::name)" in
      'mac')
        curl https://www.toptal.com/developers/gitignore/api/macos >> ~/.gitignore
        ;;
      'debian')
        curl https://www.toptal.com/developers/gitignore/api/linux >> ~/.gitignore
        ;;
      'linux')
        curl https://www.toptal.com/developers/gitignore/api/linux >> ~/.gitignore
        ;;
    esac
  else
    echo "[git] skipping setting up .gitignore; no curl"
  fi
}
