#!/usr/bin/env bash

import 'command::exists'
import 'file::empty'
import 'log::info'
import 'log::warn'

homebrew_formula='git'
apt_package='git'

recommended=(git-lfs)

recipe::configure() {
  log::info 'git' 'setting up .gitconfig ...'
  ./git/gitconfig.sh

  if command::exists curl; then
    log::info 'git' 'setting up .gitignore'
    if file::empty "$HOME/.gitignore"; then
      echo >>"$HOME/.gitignore"
    fi

    case "$(platform::name)" in
      'mac')
        curl https://www.toptal.com/developers/gitignore/api/macos >>"$HOME/.gitignore"
        ;;
      'debian')
        curl https://www.toptal.com/developers/gitignore/api/linux >>"$HOME/.gitignore"
        ;;
      'linux')
        curl https://www.toptal.com/developers/gitignore/api/linux >>"$HOME/.gitignore"
        ;;
    esac
  else
    log::warn 'git' 'skipping setting up .gitignore; no curl'
  fi
}
