#!/usr/bin/env bash

import 'file::append'
import 'file::empty'
import 'log::error'
import 'log::info'
import 'platform::login_shell'

homebrew_formula='starship'

debian_required=(curl)

debian::install() {
  log::info 'starship' 'installing ...'
  curl -sS https://starship.rs/install.sh | sh
}

recipe::configure() {
  local login_shell
  login_shell="$(platform::login_shell)" || return 1
  case $login_shell in
    'zsh')
      log::info 'starship' 'enabling in zsh'

      local zshrc
      if setup::missing zsh; then
        zshrc="$HOME/.zshrc"
      else
        zshrc="$HOME/.zshrc.local.zsh"
      fi

      if ! file::empty "$zshrc"; then
        file::append "$zshrc" ''
      fi
      file::append "$zshrc" '# enable https://starship.rs'
      # shellcheck disable=SC2016
      # this eval is intentionally not evaluated here, hence single-quote string
      file::append "$zshrc" 'eval "$(starship init zsh)"'
      ;;
    'bash')
      log::info 'starship' 'enabling in bash'

      local bashrc="$HOME/.bashrc"
      if ! file::empty "$bashrc"; then
        file::append "$bashrc" ''
      fi
      file::append "$bashrc" '# enable https://starship.rs'
      # shellcheck disable=SC2016
      # this eval is intentionally not evaluated here, hence single-quote string
      file::append "$bashrc" 'eval "$(starship init bash)"'
      ;;
    *)
      log::error 'starship' "don't know how to enable for $login_shell"
      return 1
      ;;
  esac
}
