#!/usr/bin/env bash

source function/path/exists
source function/prompt/yes_or_no

platform::safe_link() {
  local what=$1
  local from=$2
  local to=$3

  echo "[$what] $to will be linked to $from"

  if ! path::exists "$from"; then
    echo "[$what] $from does not exist; aborting!"
    return 1
  fi

  if path::exists "$to"; then
    if path::exists "$to.old"; then
      echo "[$what] both $to and $to.old already exist; aborting!"
      return 1
    fi

    echo "[$what] $to exists; do you want to replace it (Yes / No)?"
    case $(prompt::yes_or_no) in
    Yes)
      echo "[$what] old $to will be moved to $to.old"
      mv "$to" "$to.old"
      ;;
    No)
      echo "[$what] $to will not be linked"
      return 1
      ;;
    esac
  fi

  ln -s "$from" "$to"
}
