# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# access the online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# aliases
alias ls='ls -F'
alias l='ls -AF'
alias ll='ls -lF'
alias dh='dirs -v'
alias g='git'
alias h='hg'
alias emacs='emacs -nw'
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# variables
# keep history file between sessions
HISTSIZE=10000 # to save
SAVEHIST=10000 # to load (<=HISTSIZE)
HISTFILE=~/.zsh_history
# DIRSTACKSIZE=10 # turn on if using auto_pushd option

# functions
namedir () { $1=$PWD }

# history options
setopt hist_verify # when using bang history prints line again when substitutions are made
setopt share_history # shares history between zsh's
setopt no_clobber hist_allow_clobber # don't allow to overwrite files but save command in
                                     # history which overrides NO_CLOBBER
setopt hist_reduce_blanks # remove unnecessary blanks from command when saving in history
setopt hist_no_store # don't save history and fc command executions in history
setopt hist_no_functions # don't save function definitions in history
# setopt append_history # append commands to history file when shell exits
                        # (not needed when share_history is on)
# setopt inc_append_history # append commands to history file as they are executed
                            # (not needed when share_history is on)
# setopt extended_history # save time and duration of command execution in history
                          # (doesn't work when share_history or inc_append_history is on)
# setopt hist_ignore_dups # ignore adjecent duplicate commands
# setopt hist_ignore_space # if command starts with space don't save it in history

# directory stack options
# setopt pushd_silent # pushd doesn't report stack at each invokation (use dir or dh)
setopt pushd_ignore_dups # ignore duplicates in directory stack
# setopt auto_pushd # when using cd (or auto_cd) push directory on stack
# setopt pushd_to_home # pushd without arguments goes to home

# other options
setopt auto_name_dirs # parameters which point to directory are automatically added into
                      # list of named directories
setopt auto_cd cd_able_vars # cd into directory giving explicit name or with parameter
setopt extended_glob
setopt correct # correct command names if misspelled
setopt ignore_eof # don't exit zsh when ^d is pressed on empty line

# key bindings
bindkey -e # emacs key bindings
bindkey '^[[1~' beginning-of-line
bindkey '^[[3~' delete-char
bindkey '^[[4~' end-of-line
bindkey '^[[5~' up-line-or-history
bindkey '^[[6~' down-line-or-history

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="saserr"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ant gem git git-flow mvn mercurial ruby sbt scala svn)

if [ -f ~/.zshrc.local.zsh ]; then
  source ~/.zshrc.local.zsh
fi

source $ZSH/oh-my-zsh.sh
