name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Bats
      uses: addnab/docker-run-action@v3
      with:
        image: bats/bats:latest
        options: -v ${{ github.workspace }}:/code
        run: find test/ -type f -name '*.bats' -not -regex 'test/helpers/.*' -exec bash -c 'bats "$@"' {} +

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './lib'
        check_together: 'yes'
