name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Bats
      run: ./test.sh

  test-macos:
    name: Test (Mac OS builtin bash)
    runs-on: macos-latest

    steps:
    - name: Check bash version
      run: /usr/bin/env bash -c '((${BASH_VERSINFO[0]} < 4))'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew update
        brew install coreutils findutils parallel bats-core

    - name: Bats
      run: ./test.sh --local

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: ShellCheck
      run: ./shellcheck.sh

    - name: shfmt
      run: ./shfmt.sh
