name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      uses: addnab/docker-run-action@v3
      with:
          image: bats/bats:latest
          options: -v ${{ github.workspace }}:/code
          run: bats test -r
